### ISSUE TITLE
MissingInputException when merging with 0.7.2

### ISSUE THREAD

**Issue by danilexn** [rajewsky-lab/spacemake#69]
When I try to merge two samples with spacemake 0.7.2, I first run:

```bash
spacemake projects merge_samples \
--merged_project_id <project> --merged_sample_id <sample_merged> \
--project_id_list <project> \
--sample_id_list <sample_a> <sample_b> 
```
(the IDs were replaced by <placeholders>)

Then, when running `spacemake run`, it exits upon the following exception:

```
WorkflowError:
MissingInputException: Missing input files for rule symlinks:
NO_BAM_SYMLINKS_for_projects/<project>/processed_data/<sample_merged>/illumina/complete_data/unaligned_bc_tagged.bam
WorkflowError:
    MissingInputException: Missing input files for rule link_raw_reads:
    none
    MissingInputException: Missing input files for rule demultiplex_data:
```
